### PR TITLE
Resolve 2 issues

### LINKED ISSUE #197: Left margin for hamburger

### LINKED ISSUE #212: Title element missing in iframe

### PR DESCRIPTION
**Pull request by Kej-r03**
Fix #197
The change in event_item.html was just a sample change.
The left margin has been added in header.css file.

Fix #212 
Add title attribute inside iframe tag.

### CODE REVIEW

**Review by Yavnikaa — COMMENTED** [review]
This css should be changed in the menu file, and not in the header.

**Review by Yavnikaa — COMMENTED** [review]
The chage in `event-item.html` test file is not required.

**Comment by Yavnikaa** [comment]
@Kej-r03 jaldi karde changes please. We'll merge it then!

**Comment by Kej-r03** [comment]
> This css should be changed in the menu file, and not in the header.

But the left margin is already present in the menu file sidebar...it was missing in the header file, as what u told me in the lab too
Please confirm if i do need to make any changes in that

**Comment by ParitoshKabra** [comment]
Fixed

**Pull request closed without merging**
